spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg-enum-demo
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
        order_inserts: true
        order_updates: true
        jdbc:
          lob.non_contextual_creation: true
          batch_size: 20
          fetch_size: 20
          batch_versioned_data: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
logging:
  level:
#    root: debug
    jdbc:
      sqlonly: info
      resultsettable: info
      sqltiming: fatal
      audit: fatal
      resultset: fatal
      connection: fatal
    org:
      springframework:
        orm:
          jpa: debug
